/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppCard: typeof import('./src/components/common/AppCard.vue')['default']
    Application: typeof import('./src/components/application/Application.vue')['default']
    AppPage: typeof import('./src/components/common/AppPage.vue')['default']
    CommonWrapper: typeof import('./src/components/common/CommonWrapper.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    JayIcon: typeof import('./src/components/common/JayIcon.vue')['default']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NWatermark: typeof import('naive-ui')['NWatermark']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheFooter: typeof import('./src/components/common/TheFooter.vue')['default']
    TheLogo: typeof import('./src/components/common/TheLogo.vue')['default']
    Watermark: typeof import('./src/components/common/Watermark.vue')['default']
  }
}
