/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ApiSelect: typeof import('./../src/components/Form/src/components/ApiSelect.vue')['default']
    ApiTree: typeof import('./../src/components/Form/src/components/ApiTree.vue')['default']
    ApiTreeSelect: typeof import('./../src/components/Form/src/components/ApiTreeSelect.vue')['default']
    AppCard: typeof import('./../src/components/common/AppCard.vue')['default']
    Application: typeof import('./../src/components/application/Application.vue')['default']
    AppPage: typeof import('./../src/components/common/AppPage.vue')['default']
    BasicDrawer: typeof import('./../src/components/Drawer/src/BasicDrawer.vue')['default']
    BasicDrawerFooter: typeof import('./../src/components/Drawer/src/components/BasicDrawerFooter.vue')['default']
    BasicForm: typeof import('./../src/components/Form/src/BasicForm.vue')['default']
    BasicModal: typeof import('./../src/components/Modal/src/BasicModal.vue')['default']
    BasicModalFooter: typeof import('./../src/components/Modal/src/components/BasicModalFooter.vue')['default']
    CommonWrapper: typeof import('./../src/components/common/CommonWrapper.vue')['default']
    DatePicker: typeof import('./../src/components/Form/src/components/DatePicker.vue')['default']
    HelloWorld: typeof import('./../src/components/HelloWorld.vue')['default']
    IconPicker: typeof import('./../src/components/Form/src/components/IconPicker.vue')['default']
    JayIcon: typeof import('./../src/components/common/JayIcon.vue')['default']
    MutiDatePicker: typeof import('./../src/components/modules/MutiDatePicker/MutiDatePicker.vue')['default']
    RoleUserSelect: typeof import('./../src/components/modules/RoleUserSelect/RoleUserSelect.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Src: typeof import('./../src/components/Description/src/index.vue')['default']
    Table: typeof import('./../src/components/Table/src/Table.vue')['default']
    TheLogo: typeof import('./../src/components/common/TheLogo.vue')['default']
    Toolbar: typeof import('./../src/components/Table/src/components/Toolbar.vue')['default']
    WaterMark: typeof import('./../src/components/common/WaterMark.vue')['default']
  }
}
